name: Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  Params:
    uses: amirainvest/amirainvest_com/.github/workflows/params.yml@main

  check_if_pr_merged_or_closed:
    needs: Params
    runs-on: ubuntu-20.04
    steps:
      - name: Check if PR merged
        if: needs.Params.outputs.pr_merged != 'true'
        run: exit 1

  tag_release:
    needs: check_if_pr_merged_or_closed
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Install Poetry
        run: pip3 install poetry

      - name: Bump version
        run: poetry version minor
        working-directory: ./src/common_amirainvest_com

      - name: Set git config
        run: |
          git config --global user.name 'Peter Hoburg'
          git config --global user.email 'peterHoburg@users.noreply.github.com'

      - name: Add changed file
        run: git add pyproject.toml
        working-directory: ./src/common_amirainvest_com

      - name: Git commit
        run: git commit -m "Auto update common pacage to $(poetry version -s)"
        working-directory: ./src/common_amirainvest_com


      - name: Git push
        run: git push

      - name: Git tag
        run: git tag $(poetry version -s)
        working-directory: ./src/common_amirainvest_com

      - name: Push tags
        run: git push origin --tags

  tests:
    needs: tag_release
    uses: amirainvest/amirainvest_com/.github/workflows/tests.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  ecr_images:
    needs: tests
    uses: amirainvest/amirainvest_com/.github/workflows/push_containers.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  run_terraform:
    needs: ecr_images
    uses: amirainvest/amirainvest_com/.github/workflows/activate_terraform_with_api.yml@main
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
