"""brokerage

Revision ID: 009d5c43b993
Revises: 15b1b78d1952
Create Date: 2022-02-02 06:53:33.166623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '009d5c43b993'
down_revision = '15b1b78d1952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brokerage_jobs', sa.Column('error', sa.String(), nullable=True))
    op.drop_column('brokerage_jobs', 'params')
    op.add_column('brokerage_jobs', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'brokerage_jobs', 'params',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=True
    )
    op.drop_column('brokerage_jobs', 'error')
    # ### end Alembic commands ###
