"""posts update

Revision ID: 0dd945959ef9
Revises: a0476358ec16
Create Date: 2022-02-11 04:59:50.203079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dd945959ef9'
down_revision = 'a0476358ec16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('platform_display_name', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('platform_img_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('platform_profile_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('twitter_handle', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('platform_post_url', sa.String(), nullable=True))
    op.drop_column('posts', 'profile_url')
    op.drop_column('posts', 'profile_img_url')
    op.drop_column('posts', 'chip_labels')
    op.drop_column('posts', 'text')
    op.drop_column('posts', 'html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('html', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('chip_labels', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('profile_img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'platform_post_url')
    op.drop_column('posts', 'twitter_handle')
    op.drop_column('posts', 'platform_profile_url')
    op.drop_column('posts', 'platform_img_url')
    op.drop_column('posts', 'platform_display_name')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
