"""intial

Revision ID: 1990d1bbf8d3
Revises: 0003b6f341ca
Create Date: 2022-02-03 23:32:04.019685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1990d1bbf8d3'
down_revision = '0003b6f341ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sub',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('users_sub_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_sub_key', 'users', ['sub'])
    op.alter_column('users', 'sub',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
