"""schema update

Revision ID: 19b3dd500f0c
Revises: 98b0e5f358c5
Create Date: 2021-12-27 14:42:27.057741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "19b3dd500f0c"
down_revision = "98b0e5f358c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "running", "succeeded", "failed", name="historicaljobsstatus"), nullable=False
        ),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("params", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.alter_column("twitter_users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "deleted_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column("twitter_users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("historical_jobs")
    # ### end Alembic commands ###
