"""remove body

Revision ID: 27dd71e20b55
Revises: a65d664c3658
Create Date: 2022-02-19 23:27:32.625506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27dd71e20b55'
down_revision = 'a65d664c3658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'market_holidays', ['id'])
    op.drop_column('notifications', 'body')
    op.create_unique_constraint(None, 'security_information', ['id'])
    op.alter_column('users', 'public_holdings_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_performance_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_profile_deactivate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_trades_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'public_trades_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_profile_deactivate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_performance_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_holdings_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'security_information', type_='unique')
    op.add_column('notifications', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'market_holidays', type_='unique')
    # ### end Alembic commands ###
