"""Company updates

Revision ID: 2bd2d05937cf
Revises: 3cde2bf6392a
Create Date: 2022-02-14 17:10:49.404386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd2d05937cf'
down_revision = '3cde2bf6392a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('id')
    )
    op.create_table('security_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('average_total_volume', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('change', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('change_percentage', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('close_source', sa.String(), nullable=True),
    sa.Column('close_time', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('delayed_price', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('delayed_price_time', sa.Integer(), nullable=True),
    sa.Column('extended_change', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('extended_change_percentage', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('extended_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('extended_price_time', sa.Integer(), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('high_source', sa.String(), nullable=True),
    sa.Column('high_time', sa.Integer(), nullable=True),
    sa.Column('iex_ask_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('iex_ask_size', sa.Integer(), nullable=True),
    sa.Column('iex_bid_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('iex_bid_size', sa.Integer(), nullable=True),
    sa.Column('iex_close', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('iex_close_time', sa.Integer(), nullable=True),
    sa.Column('iex_last_updated', sa.Integer(), nullable=True),
    sa.Column('iex_market_percentage', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('iex_open', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('iex_open_time', sa.Integer(), nullable=True),
    sa.Column('iex_realtime_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('iex_real_time_size', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('iex_volume', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('last_trade_time', sa.Integer(), nullable=True),
    sa.Column('latest_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('latest_source', sa.String(), nullable=True),
    sa.Column('latest_time', sa.String(), nullable=True),
    sa.Column('latest_update', sa.Integer(), nullable=True),
    sa.Column('latest_volume', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('low_source', sa.String(), nullable=True),
    sa.Column('low_time', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('odd_lot_delayed_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('odd_lot_delayed_price_time', sa.Integer(), nullable=True),
    sa.Column('open', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('open_time', sa.Integer(), nullable=True),
    sa.Column('open_source', sa.String(), nullable=True),
    sa.Column('pe_ratio', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('previous_close', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('previous_volume', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('volume', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('week_high_52', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('week_low_52', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('ytd_change', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('security_id')
    )
    op.add_column('securities', sa.Column('founding_date', sa.Date(), nullable=True))
    op.add_column('securities', sa.Column('asset_type', sa.String(), nullable=True))
    op.create_index(op.f('security_prices_price_time_idx'), 'security_prices', ['price_time'], postgresql_using='brin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities', 'asset_type')
    op.drop_column('securities', 'founding_date')
    op.drop_table('security_information')
    op.drop_table('market_holidays')
    # ### end Alembic commands ###
