"""Added chip_labels to Posts

Revision ID: 2ec5de1da021
Revises: 5b040aa8b85b
Create Date: 2022-01-11 03:05:36.964889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec5de1da021'
down_revision = '5b040aa8b85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('chip_labels', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'chip_labels')
    # ### end Alembic commands ###
