"""Changed UC

Revision ID: 30c5f8b58e55
Revises: becc503759f5
Create Date: 2022-02-17 22:49:20.696052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c5f8b58e55'
down_revision = 'becc503759f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('financial_account_holdings_hist_account_id_security_id_date_key', 'financial_account_holdings_history', type_='unique')
    op.create_unique_constraint(None, 'financial_account_holdings_history', ['id'])
    op.create_unique_constraint(None, 'financial_account_holdings_history', ['account_id', 'security_id', 'holding_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_account_holdings_history', type_='unique')
    op.drop_constraint(None, 'financial_account_holdings_history', type_='unique')
    op.create_unique_constraint('financial_account_holdings_hist_account_id_security_id_date_key', 'financial_account_holdings_history', ['account_id', 'security_id', 'date'])
    # ### end Alembic commands ###
