"""subscription level added

Revision ID: 40d456728c4b
Revises: cedb27a639c0
Create Date: 2022-01-14 23:51:05.043518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '40d456728c4b'
down_revision = 'cedb27a639c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    subscriptionlevel = postgresql.ENUM('standard', 'premium', name='subscriptionlevel', create_type=False)
    subscriptionlevel.create(op.get_bind())
    op.add_column('user_subscriptions', sa.Column('subscription_level', sa.Enum('standard', 'premium', name='subscriptionlevel'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'subscription_level')
    subscriptionlevel = postgresql.ENUM('standard', 'premium', name='subscriptionlevel', create_type=False)
    subscriptionlevel.drop(op.get_bind())
    # ### end Alembic commands ###
