"""notifications unique constraints

Revision ID: 413a0e1fdc1b
Revises: f752a6542a12
Create Date: 2022-02-05 20:49:15.040583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413a0e1fdc1b'
down_revision = 'f752a6542a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notification_settings', ['id'])
    op.create_unique_constraint(None, 'notifications', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_constraint(None, 'notification_settings', type_='unique')
    # ### end Alembic commands ###
