"""updated husk requests schema

Revision ID: 4d4fae29a19c
Revises: f5af631e5a8e
Create Date: 2022-01-13 06:09:21.955878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4fae29a19c'
down_revision = 'f5af631e5a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('husk_requests', sa.Column('platform_id', sa.String(), nullable=False))
    op.add_column('husk_requests', sa.Column('platform', sa.Enum('youtube', 'substack', 'twitter', name='platforms'), nullable=False))
    op.drop_column('husk_requests', 'substack_username')
    op.drop_column('husk_requests', 'twitter_user_id')
    op.drop_column('husk_requests', 'youtube_channel_id')
    op.add_column('posts', sa.Column('chip_labels', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'chip_labels')
    op.add_column('husk_requests', sa.Column('youtube_channel_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('husk_requests', sa.Column('twitter_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('husk_requests', sa.Column('substack_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('husk_requests', 'platform')
    op.drop_column('husk_requests', 'platform_id')
    # ### end Alembic commands ###
