"""something

Revision ID: 4f2d7e9d45b9
Revises: 40d456728c4b
Create Date: 2022-01-21 20:22:38.718843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2d7e9d45b9'
down_revision = '17326bbd2fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('collect', sa.Boolean(), nullable=False))
    op.add_column('securities', sa.Column('currency', sa.String(), nullable=True))
    op.alter_column('securities', 'ticker_symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_securities_collect'), 'securities', ['collect'], unique=False)
    op.drop_column('securities', 'iso_currency_code')
    op.drop_column('securities', 'unofficial_currency_code')
    op.add_column('security_prices', sa.Column('security_id', sa.Integer(), nullable=False))
    op.drop_constraint('security_prices_price_time_securities_id_key', 'security_prices', type_='unique')
    op.create_unique_constraint(None, 'security_prices', ['price_time', 'security_id'])
    op.drop_constraint('security_prices_securities_id_fkey', 'security_prices', type_='foreignkey')
    op.create_foreign_key(None, 'security_prices', 'securities', ['security_id'], ['id'])
    op.drop_column('security_prices', 'securities_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_prices', sa.Column('securities_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'security_prices', type_='foreignkey')
    op.create_foreign_key('security_prices_securities_id_fkey', 'security_prices', 'securities', ['securities_id'], ['id'])
    op.drop_constraint(None, 'security_prices', type_='unique')
    op.create_unique_constraint('security_prices_price_time_securities_id_key', 'security_prices', ['price_time', 'securities_id'])
    op.drop_column('security_prices', 'security_id')
    op.add_column('securities', sa.Column('unofficial_currency_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('iso_currency_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_securities_collect'), table_name='securities')
    op.alter_column('securities', 'ticker_symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('securities', 'currency')
    op.drop_column('securities', 'collect')
    # ### end Alembic commands ###
