"""Added chip label to Users

Revision ID: 5b040aa8b85b
Revises: 1162ff2ec1e8
Create Date: 2022-01-11 02:51:26.511245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b040aa8b85b'
down_revision = '1162ff2ec1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chip_labels', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chip_labels')
    # ### end Alembic commands ###
