"""test

Revision ID: 65efffff71d3
Revises: f752a6542a12
Create Date: 2022-02-11 18:35:49.715389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65efffff71d3'
down_revision = 'f752a6542a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('id')
    )
    op.create_table('financial_account_holdings_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plaid_security_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('price_time', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['plaid_security_id'], ['plaid_securities.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_account_holdings_history')
    op.drop_table('market_holidays')
    # ### end Alembic commands ###
