"""Company Update

Revision ID: 66f7f028b573
Revises: 3cde2bf6392a
Create Date: 2022-02-16 17:05:02.475968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '66f7f028b573'
down_revision = '3cde2bf6392a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'market_holidays',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('settlement_date', sa.DateTime(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('date'),
        sa.UniqueConstraint('id')
    )
    op.create_table(
        'security_information',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('security_id', sa.Integer(), nullable=False),
        sa.Column('average_total_volume', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('change', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('change_percentage', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('close', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('close_source', sa.String(), nullable=True),
        sa.Column('close_time', sa.Integer(), nullable=True),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('delayed_price', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('delayed_price_time', sa.Integer(), nullable=True),
        sa.Column('extended_change', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('extended_change_percentage', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('extended_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('extended_price_time', sa.Integer(), nullable=True),
        sa.Column('high', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('high_source', sa.String(), nullable=True),
        sa.Column('high_time', sa.Integer(), nullable=True),
        sa.Column('iex_ask_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('iex_ask_size', sa.Integer(), nullable=True),
        sa.Column('iex_bid_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('iex_bid_size', sa.Integer(), nullable=True),
        sa.Column('iex_close', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('iex_close_time', sa.Integer(), nullable=True),
        sa.Column('iex_last_updated', sa.Integer(), nullable=True),
        sa.Column('iex_market_percentage', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('iex_open', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('iex_open_time', sa.Integer(), nullable=True),
        sa.Column('iex_realtime_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('iex_real_time_size', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('iex_volume', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('last_trade_time', sa.Integer(), nullable=True),
        sa.Column('latest_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('latest_source', sa.String(), nullable=True),
        sa.Column('latest_time', sa.String(), nullable=True),
        sa.Column('latest_update', sa.Integer(), nullable=True),
        sa.Column('latest_volume', sa.DECIMAL(precision=19, scale=5), nullable=True),
        sa.Column('low', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('low_source', sa.String(), nullable=True),
        sa.Column('low_time', sa.Integer(), nullable=True),
        sa.Column('market_cap', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('odd_lot_delayed_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('odd_lot_delayed_price_time', sa.Integer(), nullable=True),
        sa.Column('open', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('open_time', sa.Integer(), nullable=True),
        sa.Column('open_source', sa.String(), nullable=True),
        sa.Column('pe_ratio', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('previous_close', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('previous_volume', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('volume', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('week_high_52', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('week_low_52', sa.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column('ytd_change', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('security_id')
    )
    op.alter_column(
        'financial_account_current_holdings', 'latest_price_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=False
    )
    op.alter_column(
        'financial_account_transactions', 'posting_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False
    )
    op.alter_column(
        'plaid_security_prices', 'price_time',
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False
    )
    op.add_column('securities', sa.Column('founding_date', sa.Date(), nullable=True))
    op.add_column('securities', sa.Column('asset_type', sa.String(), nullable=True))
    op.alter_column(
        'security_prices', 'price_time',
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False
    )
    op.create_index(op.f('security_prices_price_time_idx'), 'security_prices', ['price_time'], postgresql_using='brin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'security_prices', 'price_time',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False
    )
    op.drop_column('securities', 'asset_type')
    op.drop_column('securities', 'founding_date')
    op.alter_column(
        'plaid_security_prices', 'price_time',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False
    )
    op.alter_column(
        'financial_account_transactions', 'posting_date',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False
    )
    op.alter_column(
        'financial_account_current_holdings', 'latest_price_date',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.drop_table('security_information')
    op.drop_table('market_holidays')
    op.drop_index('security_prices_price_time_idx')
    # ### end Alembic commands ###
