"""notification models

Revision ID: 8008e95ea46d
Revises: 7675c2772862
Create Date: 2022-01-22 20:39:02.421010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8008e95ea46d'
down_revision = '7675c2772862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('mention', sa.Boolean(), nullable=False),
    sa.Column('upvotes', sa.Boolean(), nullable=False),
    sa.Column('shared_change', sa.Boolean(), nullable=False),
    sa.Column('watchlist_price', sa.Boolean(), nullable=False),
    sa.Column('shared_price', sa.Boolean(), nullable=False),
    sa.Column('email_trades', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True))
    op.alter_column('notifications', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'redirect_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'notifications', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='unique')
    op.alter_column('notifications', 'redirect_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'is_deleted')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
