"""added config tables

Revision ID: 8489d4e44fe7
Revises: cedb27a639c0
Create Date: 2022-01-14 22:47:36.891109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8489d4e44fe7'
down_revision = '9ce55a7936ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('chip_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('trading_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('users', sa.Column('trading_strategy', sa.String(), nullable=True))
    op.drop_column('users', 'interests_growth')
    op.drop_column('users', 'interests_long_term')
    op.drop_column('users', 'interests_short_term')
    op.drop_column('users', 'interests_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interests_value', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('interests_short_term', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('interests_long_term', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('interests_growth', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'trading_strategy')
    op.drop_table('trading_strategies')
    op.drop_table('chip_labels')
    op.drop_table('benchmarks')
    # ### end Alembic commands ###
