"""notification models

Revision ID: 8dd8dd490e31
Revises: 8008e95ea46d
Create Date: 2022-01-22 21:17:45.271737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd8dd490e31'
down_revision = '8008e95ea46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notification_settings', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_settings', type_='unique')
    # ### end Alembic commands ###
