"""substack update II

Revision ID: 90f6c99d7f4d
Revises: ccc968f2bb6f
Create Date: 2022-02-12 05:23:55.178341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f6c99d7f4d'
down_revision = 'ccc968f2bb6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substack_articles', sa.Column('username', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'substack_articles', ['username'])
    op.create_foreign_key(None, 'substack_articles', 'substack_users', ['username'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'substack_articles', type_='foreignkey')
    op.drop_constraint(None, 'substack_articles', type_='unique')
    op.drop_column('substack_articles', 'username')
    # ### end Alembic commands ###
