"""Time

Revision ID: 9449e4eea58d
Revises: 2bd2d05937cf
Create Date: 2022-02-16 15:56:08.771026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9449e4eea58d'
down_revision = '2bd2d05937cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'market_holidays', ['id'])
    op.create_unique_constraint(None, 'security_information', ['id'])
    op.alter_column('security_prices', 'price_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_prices', 'price_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'security_information', type_='unique')
    op.drop_constraint(None, 'market_holidays', type_='unique')
    # ### end Alembic commands ###
