"""Removed constraint

Revision ID: 993656992854
Revises: f7b4bb8dd3aa
Create Date: 2022-03-08 15:03:45.070979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993656992854'
down_revision = 'f7b4bb8dd3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bad_plaid_items', ['id'])
    op.drop_constraint('securities_human_readable_name_key', 'securities', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('securities_human_readable_name_key', 'securities', ['human_readable_name'])
    op.drop_constraint(None, 'bad_plaid_items', type_='unique')
    # ### end Alembic commands ###
