"""substack update III

Revision ID: a6191ed9752e
Revises: 90f6c99d7f4d
Create Date: 2022-02-12 05:26:30.748089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6191ed9752e'
down_revision = '90f6c99d7f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('substack_articles_username_key', 'substack_articles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('substack_articles_username_key', 'substack_articles', ['username'])
    # ### end Alembic commands ###
