"""user_nomenclature

Revision ID: a65d664c3658
Revises: 66f7f028b573
Create Date: 2022-02-16 21:18:45.724156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65d664c3658'
down_revision = '66f7f028b573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_holdings_activate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('public_performance_activate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('public_profile_deactivate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('public_trades_activate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('users', 'public_performance')
    op.drop_column('users', 'public_trades')
    op.drop_column('users', 'public_holdings')
    op.drop_column('users', 'public_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_profile', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('public_holdings', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('public_trades', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('public_performance', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'public_trades_activate')
    op.drop_column('users', 'public_profile_deactivate')
    op.drop_column('users', 'public_performance_activate')
    op.drop_column('users', 'public_holdings_activate')
    # ### end Alembic commands ###
