"""Change notifications body type

Revision ID: accc23c40cda
Revises: a65d664c3658
Create Date: 2022-02-20 02:15:58.017310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accc23c40cda'
down_revision = 'a65d664c3658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'market_holidays', ['id'])
    op.alter_column('notifications', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'security_information', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'security_information', type_='unique')
    op.alter_column('notifications', 'body',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'market_holidays', type_='unique')
    # ### end Alembic commands ###
