"""financial accounts update

Revision ID: b37911d2aa53
Revises: b803a4b2c7cd
Create Date: 2022-01-05 00:29:48.739481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b37911d2aa53'
down_revision = 'b803a4b2c7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_account_current_holdings', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'financial_account_current_holdings', ['account_id', 'security_id'])
    op.create_foreign_key(None, 'financial_account_current_holdings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_account_current_holdings', type_='foreignkey')
    op.drop_constraint(None, 'financial_account_current_holdings', type_='unique')
    op.drop_column('financial_account_current_holdings', 'user_id')
    # ### end Alembic commands ###
