"""Portfolio

Revision ID: becc503759f5
Revises: a65d664c3658
Create Date: 2022-02-17 16:59:06.210269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'becc503759f5'
down_revision = 'a65d664c3658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_account_holdings_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plaid_security_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('holding_date', sa.Date(), nullable=False),
    sa.Column('cost_basis', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['plaid_security_id'], ['plaid_securities.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'security_id', 'date'),
    sa.UniqueConstraint('id')
    )
    op.drop_constraint('financial_account_current_holdings_user_id_fkey', 'financial_account_current_holdings', type_='foreignkey')
    op.drop_column('financial_account_current_holdings', 'user_id')
    op.add_column('financial_account_transactions', sa.Column('plaid_security_id', sa.Integer(), nullable=True))
    op.drop_constraint('financial_account_transactions_security_id_fkey', 'financial_account_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'financial_account_transactions', 'plaid_securities', ['plaid_security_id'], ['id'])
    op.drop_column('financial_account_transactions', 'security_id')
    op.create_unique_constraint(None, 'market_holidays', ['id'])
    op.add_column('plaid_securities', sa.Column('security_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plaid_securities', 'securities', ['security_id'], ['id'])
    op.create_unique_constraint(None, 'security_information', ['id'])
    op.alter_column('users', 'public_holdings_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_performance_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_profile_deactivate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_trades_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'public_trades_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_profile_deactivate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_performance_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'public_holdings_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'security_information', type_='unique')
    op.drop_constraint(None, 'plaid_securities', type_='foreignkey')
    op.drop_column('plaid_securities', 'security_id')
    op.drop_constraint(None, 'market_holidays', type_='unique')
    op.add_column('financial_account_transactions', sa.Column('security_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'financial_account_transactions', type_='foreignkey')
    op.create_foreign_key('financial_account_transactions_security_id_fkey', 'financial_account_transactions', 'plaid_securities', ['security_id'], ['id'])
    op.drop_column('financial_account_transactions', 'plaid_security_id')
    op.add_column('financial_account_current_holdings', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('financial_account_current_holdings_user_id_fkey', 'financial_account_current_holdings', 'users', ['user_id'], ['id'])
    op.drop_table('financial_account_holdings_history')
    # ### end Alembic commands ###
