"""search fields

Revision ID: bef1b5faeb58
Revises: 993656992854
Create Date: 2022-03-08 23:25:39.488140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef1b5faeb58'
down_revision = '993656992854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('benchmark_alias', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('search_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'securities', ['benchmark_alias'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'securities', type_='unique')
    op.drop_column('securities', 'search_name')
    op.drop_column('securities', 'benchmark_alias')
    # ### end Alembic commands ###
