"""Brokerage update


Revision ID: c25916ed94e8
Revises: 009d5c43b993
Create Date: 2022-02-02 07:37:29.338387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25916ed94e8'
down_revision = '009d5c43b993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('financial_account_current_holdings_security_id_fkey', 'financial_account_current_holdings', type_='foreignkey')
    op.create_foreign_key(None, 'financial_account_current_holdings', 'plaid_securities', ['security_id'], ['id'])
    op.drop_constraint('financial_account_transactions_security_id_fkey', 'financial_account_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'financial_account_transactions', 'plaid_securities', ['security_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_account_transactions', type_='foreignkey')
    op.create_foreign_key('financial_account_transactions_security_id_fkey', 'financial_account_transactions', 'securities', ['security_id'], ['id'])
    op.drop_constraint(None, 'financial_account_current_holdings', type_='foreignkey')
    op.create_foreign_key('financial_account_current_holdings_security_id_fkey', 'financial_account_current_holdings', 'securities', ['security_id'], ['id'])
    # ### end Alembic commands ###
