"""Removed Constraint on Financial Accounts

Revision ID: c6a7ca5b91c3
Revises: b37911d2aa53
Create Date: 2022-01-06 17:37:56.740970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a7ca5b91c3'
down_revision = 'b37911d2aa53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('financial_account_transaction_account_id_security_id_postin_key', 'financial_account_transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('financial_account_transaction_account_id_security_id_postin_key', 'financial_account_transactions', ['account_id', 'security_id', 'posting_date'])
    # ### end Alembic commands ###
