"""substack update

Revision ID: ccc968f2bb6f
Revises: 0dd945959ef9
Create Date: 2022-02-12 05:23:11.157109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc968f2bb6f'
down_revision = '0dd945959ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('substack_articles_substack_user_fkey', 'substack_articles', type_='foreignkey')
    op.drop_column('substack_articles', 'substack_user')
    op.create_unique_constraint(None, 'substack_users', ['username'])
    op.drop_column('substack_users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substack_users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'substack_users', type_='unique')
    op.add_column('substack_articles', sa.Column('substack_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('substack_articles_substack_user_fkey', 'substack_articles', 'substack_users', ['substack_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
