"""removed date

Revision ID: cd018b6366f8
Revises: 30c5f8b58e55
Create Date: 2022-02-17 22:55:51.062970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd018b6366f8'
down_revision = '30c5f8b58e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_account_holdings_history', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_account_holdings_history', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
