"""husk request updates

Revision ID: d722b7608aa2
Revises: 9ce55a7936ce
Create Date: 2022-01-20 01:46:40.266249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd722b7608aa2'
down_revision = '40d456728c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('husk_requests', sa.Column('provided_name', sa.String(), nullable=False))
    op.add_column('husk_requests', sa.Column('platform_id', sa.String(), nullable=False))
    huskplatforms = postgresql.ENUM('youtube', 'substack', 'twitter', name='huskplatforms')
    huskplatforms.create(op.get_bind())
    op.add_column('husk_requests', sa.Column('platform', sa.Enum('youtube', 'substack', 'twitter', name='huskplatforms'), nullable=False))
    op.drop_column('husk_requests', 'substack_username')
    op.drop_column('husk_requests', 'twitter_user_id')
    op.drop_column('husk_requests', 'youtube_channel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('husk_requests', sa.Column('youtube_channel_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('husk_requests', sa.Column('twitter_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('husk_requests', sa.Column('substack_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    huskplatforms = postgresql.ENUM('youtube', 'substack', 'twitter', name='huskplatforms')
    huskplatforms.drop(op.get_bind())
    op.drop_column('husk_requests', 'platform')
    op.drop_column('husk_requests', 'platform_id')
    op.drop_column('husk_requests', 'provided_name')
    # ### end Alembic commands ###
