"""uc on user subs

Revision ID: df5a74cf9645
Revises: a65d664c3658
Create Date: 2022-02-21 20:50:20.597040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5a74cf9645'
down_revision = 'a65d664c3658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_sub', 'user_subscriptions', ['subscriber_id', 'creator_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_sub', 'user_subscriptions', type_='unique')
    # ### end Alembic commands ###
