"""market data tables

Revision ID: e714c8f829dd
Revises: f5af631e5a8e
Create Date: 2022-01-13 00:31:14.825989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e714c8f829dd'
down_revision = 'f5af631e5a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaid_security_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker_symbol', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('cusip', sa.String(), nullable=True),
    sa.Column('sedol', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('plaid_institution_security_id', sa.String(), nullable=True),
    sa.Column('is_cash_equivalent', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('iso_currency_code', sa.String(), nullable=True),
    sa.Column('unofficial_currency_code', sa.String(), nullable=True),
    sa.Column('plaid_update_type', sa.String(), nullable=True),
    sa.Column('plaid_webhook_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['financial_institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('plaid_security_id'),
    sa.UniqueConstraint('ticker_symbol')
    )
    op.create_table('plaid_security_prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plaid_securities_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('price_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['plaid_securities_id'], ['plaid_securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('price_time', 'plaid_securities_id')
    )
    op.add_column('securities', sa.Column('exchange', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('description', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('website', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('ceo', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('issue_type', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('sector', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('primary_sic_code', sa.BigInteger(), nullable=True))
    op.add_column('securities', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('securities', sa.Column('address', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('securities', sa.Column('open_price', sa.DECIMAL(precision=19, scale=4), nullable=False))
    op.add_column('securities', sa.Column('close_price', sa.DECIMAL(precision=19, scale=4), nullable=False))
    op.drop_constraint('securities_plaid_security_id_key', 'securities', type_='unique')
    op.drop_constraint('securities_institution_id_fkey', 'securities', type_='foreignkey')
    op.drop_column('securities', 'plaid_security_id')
    op.drop_column('securities', 'isin')
    op.drop_column('securities', 'plaid_webhook_url')
    op.drop_column('securities', 'cusip')
    op.drop_column('securities', 'institution_id')
    op.drop_column('securities', 'plaid_institution_security_id')
    op.drop_column('securities', 'is_cash_equivalent')
    op.drop_column('securities', 'sedol')
    op.drop_column('securities', 'plaid_update_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('plaid_update_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('sedol', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('is_cash_equivalent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('plaid_institution_security_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('cusip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('plaid_webhook_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('isin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('plaid_security_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('securities_institution_id_fkey', 'securities', 'financial_institutions', ['institution_id'], ['id'])
    op.create_unique_constraint('securities_plaid_security_id_key', 'securities', ['plaid_security_id'])
    op.drop_column('securities', 'close_price')
    op.drop_column('securities', 'open_price')
    op.drop_column('securities', 'phone')
    op.drop_column('securities', 'address')
    op.drop_column('securities', 'employee_count')
    op.drop_column('securities', 'primary_sic_code')
    op.drop_column('securities', 'sector')
    op.drop_column('securities', 'issue_type')
    op.drop_column('securities', 'ceo')
    op.drop_column('securities', 'industry')
    op.drop_column('securities', 'website')
    op.drop_column('securities', 'description')
    op.drop_column('securities', 'exchange')
    op.drop_table('plaid_security_prices')
    op.drop_table('plaid_securities')
    # ### end Alembic commands ###
