"""watchlist items

Revision ID: e92e709aaab3
Revises: df5a74cf9645
Create Date: 2022-02-26 04:04:30.600778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e92e709aaab3'
down_revision = 'df5a74cf9645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'financial_account_holdings_history', ['id'])
    op.drop_column('watchlists', 'tickers')
    op.drop_column('watchlists', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('watchlists', sa.Column('tickers', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'financial_account_holdings_history', type_='unique')
    op.drop_table('watchlist_items')
    # ### end Alembic commands ###
