"""added json body

Revision ID: e9ee4ebedfc2
Revises: 27dd71e20b55
Create Date: 2022-02-19 23:28:15.697953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ee4ebedfc2'
down_revision = '27dd71e20b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('body', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'body')
    # ### end Alembic commands ###
