"""notifications tables and settings

Revision ID: eb99d8c0cfd1
Revises: aa4e538bec47
Create Date: 2022-02-05 16:31:34.309532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb99d8c0cfd1'
down_revision = 'aa4e538bec47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('mention', sa.Boolean(), nullable=False),
    sa.Column('upvotes', sa.Boolean(), nullable=False),
    sa.Column('shared_change', sa.Boolean(), nullable=False),
    sa.Column('watchlist_price', sa.Boolean(), nullable=False),
    sa.Column('shared_price', sa.Boolean(), nullable=False),
    sa.Column('email_trades', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('notification_type', sa.Enum('trade', 'creator_join', 'amira_post', 'mention', 'upvote', 'shared_change', 'watchlist_price', 'shared_price', name='notificationtypes'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('redirect_id', sa.String(), nullable=False),
    sa.Column('mark_as_read', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
