"""watchlist_items updated_at

Revision ID: f19d90e0055d
Revises: bef1b5faeb58
Create Date: 2022-03-14 16:16:47.673675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19d90e0055d'
down_revision = 'bef1b5faeb58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_items', 'updated_at')
    # ### end Alembic commands ###
