"""added photos to posts

Revision ID: f5af631e5a8e
Revises: 5b040aa8b85b
Create Date: 2022-01-11 23:42:24.117615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5af631e5a8e'
down_revision = '5b040aa8b85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('photos', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'photos')
    # ### end Alembic commands ###
