"""notifications routes

Revision ID: f752a6542a12
Revises: aa4e538bec47
Create Date: 2022-02-05 20:48:35.626366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f752a6542a12'
down_revision = 'aa4e538bec47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('mention', sa.Boolean(), nullable=False),
    sa.Column('upvote', sa.Boolean(), nullable=False),
    sa.Column('watchlist_price', sa.Boolean(), nullable=False),
    sa.Column('shared_change', sa.Boolean(), nullable=False),
    sa.Column('shared_price', sa.Boolean(), nullable=False),
    sa.Column('email_trades', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('trade', 'creator_join', 'amira_post', 'mention', 'upvote', 'watchlist_price', 'shared_change', 'shared_price', name='notificationtypes'), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('redirect', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'notification_settings', ['id'])
    op.create_unique_constraint(None, 'notifications', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
