name: Activate Terraform with commit

on:
  workflow_call:


jobs:
  bump_version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Change src iter
        run: date -u +%c-%N > ./terraform/src_iter

      - name: git pull
        run: git pull

      - name: Set git config
        run: |
          git config --global user.name 'Peter Hoburg'
          git config --global user.email 'peterHoburg@users.noreply.github.com'

      - name: Add changed file
        run: git add ./terraform/src_iter

      - name: Git commit
        run: git commit -m "Incremented terraform/src_iter"

      - name: Git push
        run: git push
