name: Bump Package Version

on:
  workflow_call:
    inputs:
      version_bump:
        required: true
        type: string


jobs:
  bump_version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Poetry
        run: pip3 install poetry

      - name: Bump version
        run: poetry version ${{ inputs.version_bump }}

      - name: Set git config
        run: |
          git config --global user.name 'Peter Hoburg'
          git config --global user.email 'peterHoburg@users.noreply.github.com'

      - name: Add changed file
        run: git add pyproject.toml

      - name: Git commit
        run: git commit -m "Auto update package version"

      - name: Git push
        run: git push

      - name: Git tag
        run: git tag $(poetry version -s)

      - name: Push tags
        run: git push origin --tags


