name: Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed
#  push:
#    branches:
#      [ main ]


jobs:
  tests:
    uses: amirainvest/amirainvest_com/.github/workflows/tests.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  ecr_images:
    needs: tests
    uses: amirainvest/amirainvest_com/.github/workflows/push_containers.yml@main
    with:
      microservice_list: "[\"backend_amirainvest_com\", \"lambda\"]"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  run_terraform:
    needs: ecr_images
    uses: amirainvest/amirainvest_com/.github/workflows/activate_terraform_with_commit.yml@main

#  run_terraform:
#    needs: ecr_images
#    uses: amirainvest/amirainvest_com/.github/workflows/terraform.yml@main
#    with:
#      environment: "prod"
#    secrets:
#      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
