name: Set params

on:
  workflow_call:
    outputs:
      environment:
        description: "environment"
        value: ${{ jobs.Params.outputs.environment }}
      microservice_list:
        description: "microservice_list"
        value: ${{ jobs.Params.outputs.microservice_list }}
      deploy_tf:
        description: "deploy_tf"
        value: ${{ jobs.Params.outputs.deploy_tf }}
      run_deploy:
        description: "run_deploy"
        value: ${{ jobs.Params.outputs.run_deploy }}
      AWS_REGION:
        description: "AWS_REGION"
        value: ${{ jobs.Params.outputs.AWS_REGION }}

jobs:
  Params:
    runs-on: ubuntu-20.04
    outputs:
      environment: ${{ steps.params.outputs.environment }}
      microservice_list: ${{ steps.params.outputs.microservice_list }}
      deploy_tf: ${{ steps.params.outputs.deploy_tf }}
      run_deploy: ${{ steps.params.outputs.run_deploy }}
      AWS_REGION: ${{ steps.params.outputs.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate params
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        id: params
        shell: bash
        run: python ./bin/github_params.py
