name: "Python Analysis"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, staging ]

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache docker image
        id: docker-image
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/var/lib/docker
          key: docker-base

      - name: Run checks
        run: make check_docker
