name: "Python Analysis"

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run checks
        run: make check_docker
