name: "Python Analysis"

env:
  AWS_REGION: us-east-1

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

#      - name: Cache docker image
#        id: docker-image
#        uses: actions/cache@2.1.6
#        with:
#          path: ${{github.workspace}}/var/lib/docker/overlay2

      - name: Run checks
        run: make check_docker
