#name: Tests
#
#on:
#  workflow_call:
#    secrets:
#      AWS_ACCESS_KEY_ID:
#        required: true
#      AWS_SECRET_ACCESS_KEY:
#        required: true
#  pull_request:
#    branches: [ main, staging ]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          ref: "main"
#
#      - name: Run tests in docker files
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: make test
