name: Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  Params:
    runs-on: ubuntu-20.04
    outputs:
      environment: ${{ steps.params.outputs.environment }}
      microservice_list: ${{ steps.params.outputs.microservice_list }}
      deploy_tf: ${{ steps.params.outputs.deploy_tf }}
      pr_merged: ${{ steps.params.outputs.pr_merged }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate params
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        id: params
        shell: bash
        run: python ./bin/github_params.py
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:

      - name: Test
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run:  echo ${{ needs.Params.outputs.pr_merged }}
