name: Tests

on:
  workflow_call:
  pull_request:
    branches: [ main, staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create temp aws file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mkdir $HOME/.aws && sudo mount -t tmpfs -o size=2M tmpfs $HOME/.aws/ && touch $HOME/.aws/config && touch $HOME/.aws/ credentials && python3 ./bin/write_aws_file.py

      - name: Run tests in docker files
        run: make test

