name: Test
on:
  pull_request:
  workflow_dispatch:

jobs:
#  Params:
#    uses: amirainvest/amirainvest_com/.github/workflows/params.yml@main

  test:
#    needs: Params
    name: "Test"
    runs-on: ubuntu-latest
    steps:

#      - name: Test
#        run: echo ${{ needs.Params.outputs.microservice_list }}
      - name: Test
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

